version: '3.7'
name: integrate
services:
  api:
    build: ./api
    ports:
      - "8000:${API_PORT}"
    env_file: 
      - .env
      - ./api/.env.prod
    depends_on:
      db: 
        condition: service_healthy
      redis:
        condition: service_started
  db:
    build: ./db
    ports:
      - "1434:${DATABASE_PORT}"
    env_file: 
      - .env
      - ./db/.env
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U $UID_APPLICATION -P $PWD_APPLICATION -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
  redis:
    build: ./redis
    ports:
      - "6380:${REDIS_PORT}"
    env_file: 
      - .env
      - ./redis/.env