from flask_restx import Namespace
from ..resources import * 

ns_crud = Namespace("crud", "Namespace containing standard CRUD endpoints")

ns_crud.add_resource(CRUD_ConfigAgeBandDetail, '/age-band/detail/<int:id>', '/age-band/detail')
ns_crud.add_resource(CRUD_ConfigAgeBandDetail_List, '/age-band/details')
ns_crud.add_resource(CRUD_ConfigAgeBandSet, '/age-band/set/<int:id>', '/age-band/set')
ns_crud.add_resource(CRUD_ConfigAgeBandSet_List, '/age-band/sets')
ns_crud.add_resource(CRUD_ConfigAgeDistribution, '/age-distribution/detail/<int:id>', '/age-distribution/detail')
ns_crud.add_resource(CRUD_ConfigAgeDistribution_List, '/age-distribution/details')
ns_crud.add_resource(CRUD_ConfigAgeDistributionSet, '/age-distribution/set/<int:id>', '/age-distribution/set')
ns_crud.add_resource(CRUD_ConfigAgeDistributionSet_List, '/age-distribution/sets')
ns_crud.add_resource(CRUD_ConfigAgeMapperDetail, '/age-mapper/detail/<int:id>', '/age-mapper/detail')
ns_crud.add_resource(CRUD_ConfigAgeMapperDetail_List, '/age-mapper/details')
ns_crud.add_resource(CRUD_ConfigAttributeDetail, '/attribute/detail/<int:id>', '/attribute/detail')
ns_crud.add_resource(CRUD_ConfigAttributeDetail_List, '/attribute/details')
ns_crud.add_resource(CRUD_ConfigAttributeDistribution, '/attribute-distribution/detail/<int:id>', '/attribute-distribution/detail')
ns_crud.add_resource(CRUD_ConfigAttributeDistribution_List, '/attribute-distribution/details')
ns_crud.add_resource(CRUD_ConfigAttributeDistributionSet, '/attribute-distribution/set/<string:config_attr_type_code>/<int:id>', '/attribute-distribution/set/<string:config_attr_type_code>')
ns_crud.add_resource(CRUD_ConfigAttributeDistributionSet_List, '/attribute-distribution/sets/<string:config_attr_type_code>')
ns_crud.add_resource(CRUD_ConfigAttributeSet, '/attribute/set/<string:config_attr_type_code>/<int:id>', '/attribute/set/<string:config_attr_type_code>')
ns_crud.add_resource(CRUD_ConfigAttributeSet_List, '/attribute/sets/<string:config_attr_type_code>')
ns_crud.add_resource(CRUD_ConfigProduct, '/product/<int:id>', '/product')
ns_crud.add_resource(CRUD_ConfigProduct_List, '/products')





ns_crud_product = Namespace("crud-product", "Namespace of product CRUD endpoints")

ns_crud_product.add_resource(CRUD_ConfigBenefit, '/benefit/<int:id>', '/benefit')
ns_crud_product.add_resource(CRUD_ConfigBenefit_List, '/benefits')
ns_crud_product.add_resource(CRUD_ConfigBenefitCovarianceSet_List, '/benefit-covariance/sets')
ns_crud_product.add_resource(CRUD_ConfigBenefitProductVariation_List, '/benefit-variations')
ns_crud_product.add_resource(CRUD_ConfigBenefitProvision_List, '/benefit-provisions')
ns_crud_product.add_resource(CRUD_ConfigBenefitState_List, '/benefit/states')
ns_crud_product.add_resource(CRUD_ConfigCoverage, '/coverage/<int:id>', '/coverage')
ns_crud_product.add_resource(CRUD_ConfigCoverage_List, '/coverages')
ns_crud_product.add_resource(CRUD_ConfigFactor_List, '/provision/factors')
ns_crud_product.add_resource(CRUD_ConfigProductMapperDetail, '/mapper/detail/<int:id>', '/mapper/detail')
ns_crud_product.add_resource(CRUD_ConfigProductMapperDetail_List, '/mapper/details')
ns_crud_product.add_resource(CRUD_ConfigProductMapperSet, '/mapper/set/<string:config_attr_type_code>/<int:id>', '/mapper/set/<string:config_attr_type_code>')
ns_crud_product.add_resource(CRUD_ConfigProductMapperSet_List, '/mapper/sets/<string:config_attr_type_code>')
ns_crud_product.add_resource(CRUD_ConfigProductState, '/state/<int:id>', '/state')
ns_crud_product.add_resource(CRUD_ConfigProductState_List, '/states')
ns_crud_product.add_resource(CRUD_ConfigProductVariation, '/variation/<int:id>', '/variation')
ns_crud_product.add_resource(CRUD_ConfigProductVariation_List, '/variations')
ns_crud_product.add_resource(CRUD_ConfigProductVariationState, '/variation/<int:product_variation_id>/state/<int:id>', '/variation/<int:product_variation_id>/state')
ns_crud_product.add_resource(CRUD_ConfigProductVariationState_List, '/variation/states')
ns_crud_product.add_resource(CRUD_ConfigProvision, '/provision/<string:provision_type>/<int:id>', '/provision/<string:provision_type>')
ns_crud_product.add_resource(CRUD_ConfigProvision_List, '/provisions/<string:provision_type>')
ns_crud_product.add_resource(CRUD_ConfigProvisionState_List, '/provision/states')
ns_crud_product.add_resource(CRUD_ConfigProvisionUI_List, '/provision/ui-components')
ns_crud_product.add_resource(CRUD_ConfigRateGroup, '/rate-group/<int:id>', '/rate-group')
ns_crud_product.add_resource(CRUD_ConfigRateGroup_List, '/rate-groups')
ns_crud_product.add_resource(CRUD_ConfigRateGroupFaceAmounts_List, '/rate-group/face-amounts')
ns_crud_product.add_resource(CRUD_ConfigRateTable, '/rate-table/<int:id>', '/rate-table')
ns_crud_product.add_resource(CRUD_ConfigRateTable_List, '/rate-tables')
ns_crud_product.add_resource(CRUD_ConfigRelationshipMapperDetail, '/relationship-mapper/detail/<int:id>', '/relationship-mapper/detail')
ns_crud_product.add_resource(CRUD_ConfigRelationshipMapperDetail_List, '/relationship-mapper/details')
ns_crud_product.add_resource(CRUD_ConfigRelationshipMapperSet, '/relationship-mapper/set/<int:id>', '/relationship-mapper/set')
ns_crud_product.add_resource(CRUD_ConfigRelationshipMapperSet_List, '/relationship-mapper/sets')



ns_crud_provision = Namespace("crud-provision", "Namespace of provision CRUD endpoints")

ns_crud_provision.add_resource(CRUD_ConfigProvisionState, '/state/<int:id>', '/state')
ns_crud_provision.add_resource(CRUD_ConfigProvisionUI, '/ui/<int:id>', '/ui')
ns_crud_provision.add_resource(CRUD_ConfigFactor, '/factor/<int:id>', '/factor')
ns_crud_provision.add_resource(CRUD_ConfigFactorRule, '/factor/<int:factor_id>/rule/<int:id>', '/factor/<int:factor_id>/rule')
ns_crud_provision.add_resource(CRUD_ConfigFactorRule_List, '/factor/<int:factor_id>/rules')




ns_crud_benefit = Namespace("crud-benefit", "Namespace of benefit CRUD endpoints")

ns_crud_benefit.add_resource(CRUD_ConfigBenefitCovarianceDetail, '/covariance/detail/<int:id>', '/covariance/detail')
ns_crud_benefit.add_resource(CRUD_ConfigBenefitCovarianceDetail_List, '/covariance/details')
ns_crud_benefit.add_resource(CRUD_ConfigBenefitCovarianceSet, '/covariance/set/<int:id>', '/covariance/set')
ns_crud_benefit.add_resource(CRUD_ConfigBenefitDurationDetail, '/duration/detail/<int:id>', '/duration/detail')
ns_crud_benefit.add_resource(CRUD_ConfigBenefitDurationDetail_List, '/duration/details')
ns_crud_benefit.add_resource(CRUD_ConfigBenefitDurationSet, '/duration/set/<int:id>', '/duration/set')
ns_crud_benefit.add_resource(CRUD_ConfigBenefitDurationSet_List, '/duration/sets')
ns_crud_benefit.add_resource(CRUD_ConfigBenefitProductVariation, '/variation/<int:id>', '/variation')
ns_crud_benefit.add_resource(CRUD_ConfigBenefitProvision, '/provision/<int:id>', '/provision')
ns_crud_benefit.add_resource(CRUD_ConfigBenefitState, '/state/<int:id>', '/state')



ns_ref = Namespace("crud-ref", "Namespace of reference data CRUD endpoints")



ns_ref.add_resource(CRUD_RefAttrMapperType, '/attr-mapper-type/<int:id>', '/attr-mapper-type')
ns_ref.add_resource(CRUD_RefAttrMapperType_List, '/attr-mapper-types')
ns_ref.add_resource(CRUD_RefBenefit, '/benefit/<int:id>', '/benefit')
ns_ref.add_resource(CRUD_RefBenefit_List, '/benefits')
ns_ref.add_resource(CRUD_RefCensusStrategy, '/census-strategy/<int:id>', '/census-strategy')
ns_ref.add_resource(CRUD_RefCensusStrategy_List, '/census-strategies')
ns_ref.add_resource(CRUD_RefComparisonOperator, '/comparison-operator/<int:id>', '/comparison-operator')
ns_ref.add_resource(CRUD_RefComparisonOperator_List, '/comparison-operators')
ns_ref.add_resource(CRUD_RefComponentTypes, '/component-type/<int:id>', '/component-type')
ns_ref.add_resource(CRUD_RefComponentTypes_List, '/component-types')
ns_ref.add_resource(CRUD_RefDataTypes, '/data-type/<int:id>', '/data-type')
ns_ref.add_resource(CRUD_RefDataTypes_List, '/data-types')
ns_ref.add_resource(CRUD_RefFactorType, '/factor-type/<int:id>', '/factor-type')
ns_ref.add_resource(CRUD_RefFactorType_List, '/factor-types')
ns_ref.add_resource(CRUD_RefInputTypes, '/input-type/<int:id>', '/input-type')
ns_ref.add_resource(CRUD_RefInputTypes_List, '/input-types')
ns_ref.add_resource(CRUD_RefOptionality, '/optionality/<int:id>', '/optionality')
ns_ref.add_resource(CRUD_RefOptionality_List, '/optionalities')
ns_ref.add_resource(CRUD_RefPremiumFrequency, '/premium-frequency/<int:id>', '/premium-frequency')
ns_ref.add_resource(CRUD_RefPremiumFrequency_List, '/premium-frequencies')
ns_ref.add_resource(CRUD_RefProductVariation, '/product-variation/<int:id>', '/product-variation')
ns_ref.add_resource(CRUD_RefProductVariation_List, '/product-variations')
ns_ref.add_resource(CRUD_RefProvision, '/provision/<int:id>', '/provision')
ns_ref.add_resource(CRUD_RefProvision_List, '/provisions')
ns_ref.add_resource(CRUD_RefRatingStrategy, '/rating-strategy/<int:id>', '/rating-strategy')
ns_ref.add_resource(CRUD_RefRatingStrategy_List, '/rating-strategies')
ns_ref.add_resource(CRUD_RefStates, '/state/<int:id>', '/state')
ns_ref.add_resource(CRUD_RefStates_List, '/states')
ns_ref.add_resource(CRUD_RefUnitCode, '/unit-type/<int:id>', '/unit-type')
ns_ref.add_resource(CRUD_RefUnitCode_List, '/unit-types')

ns_crud.add_resource(CRUD_SelectionAgeBand, '/selection/age-band/<int:id>', '/selection/age-band')
ns_crud.add_resource(CRUD_SelectionAgeBand_List, '/selection/age-band-list')
ns_crud.add_resource(CRUD_SelectionBenefit, '/selection/benefit/<int:id>', '/selection/benefit')
ns_crud.add_resource(CRUD_SelectionBenefit_List, '/selection/benefit-list')
ns_crud.add_resource(CRUD_SelectionBenefitDuration, '/selection/benefit-duration/<int:id>', '/selection/benefit-duration')
ns_crud.add_resource(CRUD_SelectionBenefitDuration_List, '/selection/benefit-duration-list')
ns_crud.add_resource(CRUD_SelectionBenefitRateTable, '/selection/rate-table/<int:plan_id>')
ns_crud.add_resource(CRUD_SelectionCensusDetail, '/selection/census-detail/<int:id>', '/selection/census-detail')
ns_crud.add_resource(CRUD_SelectionCensusDetail_List, '/selection/census-detail-list')
ns_crud.add_resource(CRUD_SelectionCensusSet, '/selection/census-set/<int:id>', '/selection/census-set')
ns_crud.add_resource(CRUD_SelectionCensusSet_List, '/selection/census-set-list')
ns_crud.add_resource(CRUD_SelectionPlan, '/selection/plan/<int:id>', '/selection/plan')
ns_crud.add_resource(CRUD_SelectionPlan_List, '/selection/plan-list')
ns_crud.add_resource(CRUD_SelectionProvision, '/selection/provision/<int:id>', '/selection/provision')
ns_crud.add_resource(CRUD_SelectionProvision_List, '/selection/provision-list')
ns_crud.add_resource(CRUD_SelectionRateGroupFaceAmounts, '/selection/rate-group-face-amounts/<int:id>', '/selection/rate-group-face-amounts')
ns_crud.add_resource(CRUD_SelectionRateGroupFaceAmounts_List, '/selection/rate-group-face-amounts-list')

ns_crud.add_resource(SelectionCensusSet_CensusBuilder, '/selection/plan/<int:plan_id>/census/build')
ns_crud.add_resource(SelectionCensusSet_UploadFile, '/selection/plan/<int:plan_id>/census/upload')
ns_crud.add_resource(Resource_RatingPremiumCalculator, '/selection/plan/<int:plan_id>/rating/premium')