from flask_restx import Namespace
from ..resources import * 

ns_crud = Namespace("crud", "Namespace containing standard CRUD endpoints")

ns_crud.add_resource(CRUD_ConfigAgeBandDetail, '/config/age-band-detail/<int:id>', '/config/age-band-detail')
ns_crud.add_resource(CRUD_ConfigAgeBandDetail_List, '/config/age-band-detail-list')
ns_crud.add_resource(CRUD_ConfigAgeBandSet, '/config/age-band-set/<int:id>', '/config/age-band-set')
ns_crud.add_resource(CRUD_ConfigAgeBandSet_List, '/config/age-band-set-list')
ns_crud.add_resource(CRUD_ConfigAgeDistribution, '/config/age-distribution/<int:id>', '/config/age-distribution')
ns_crud.add_resource(CRUD_ConfigAgeDistribution_List, '/config/age-distribution-list')
ns_crud.add_resource(CRUD_ConfigAgeDistributionSet, '/config/age-distribution-set/<int:id>', '/config/age-distribution-set')
ns_crud.add_resource(CRUD_ConfigAgeDistributionSet_List, '/config/age-distribution-set-list')
ns_crud.add_resource(CRUD_ConfigAgeMapperDetail, '/config/age-mapper-detail/<int:id>', '/config/age-mapper-detail')
ns_crud.add_resource(CRUD_ConfigAgeMapperDetail_List, '/config/age-mapper-detail-list')
ns_crud.add_resource(CRUD_ConfigAttributeDetail, '/config/attribute-detail/<int:id>', '/config/attribute-detail')
ns_crud.add_resource(CRUD_ConfigAttributeDetail_List, '/config/attribute-detail-list')
ns_crud.add_resource(CRUD_ConfigAttributeDistribution, '/config/attribute-distribution/<int:id>', '/config/attribute-distribution')
ns_crud.add_resource(CRUD_ConfigAttributeDistribution_List, '/config/attribute-distribution-list')
ns_crud.add_resource(CRUD_ConfigAttributeDistributionSet_Gender, '/config/attribute-distribution-set-gender/<int:id>', '/config/attribute-distribution-set-gender')
ns_crud.add_resource(CRUD_ConfigAttributeDistributionSet_Gender_List, '/config/attribute-distribution-set-gender-list')
ns_crud.add_resource(CRUD_ConfigAttributeDistributionSet_SmokerStatus, '/config/attribute-distribution-set-smoker-status/<int:id>', '/config/attribute-distribution-set-smoker-status')
ns_crud.add_resource(CRUD_ConfigAttributeDistributionSet_SmokerStatus_List, '/config/attribute-distribution-set-smoker-status-list')
ns_crud.add_resource(CRUD_ConfigAttributeSet, '/config/attribute-set/<int:id>', '/config/attribute-set')
ns_crud.add_resource(CRUD_ConfigAttributeSet_Gender, '/config/attribute-set-gender/<int:id>', '/config/attribute-set-gender')
ns_crud.add_resource(CRUD_ConfigAttributeSet_SmokerStatus, '/config/attribute-set-smoker-status/<int:id>', '/config/attribute-set-smoker-status')
ns_crud.add_resource(CRUD_ConfigAttributeSet_Relationship, '/config/attribute-set-relationship/<int:id>', '/config/attribute-set-relationship')
ns_crud.add_resource(CRUD_ConfigAttributeSet_List, '/config/attribute-set-list')
ns_crud.add_resource(CRUD_ConfigAttributeSet_Gender_List, '/config/attribute-set-gender-list')
ns_crud.add_resource(CRUD_ConfigAttributeSet_SmokerStatus_List, '/config/attribute-set-smoker-status-list')
ns_crud.add_resource(CRUD_ConfigAttributeSet_Relationship_List, '/config/attribute-set-relationship-list')
ns_crud.add_resource(CRUD_ConfigBenefit, '/config/benefit/<int:id>', '/config/benefit')
ns_crud.add_resource(CRUD_ConfigBenefit_List, '/config/benefit-list')
ns_crud.add_resource(CRUD_ConfigBenefitCovarianceDetail, '/config/benefit/<int:id>', '/config/benefit-covariance-detail')
ns_crud.add_resource(CRUD_ConfigBenefitCovarianceDetail_List, '/config/benefit-covariance-detail-list')
ns_crud.add_resource(CRUD_ConfigBenefitCovarianceSet, '/config/benefit/<int:id>', '/config/benefit-covariance-set')
ns_crud.add_resource(CRUD_ConfigBenefitCovarianceSet_List, '/config/benefit-covariance-set-list')
ns_crud.add_resource(CRUD_ConfigBenefitDurationDetail, '/config/benefit-duration-detail/<int:id>', '/config/benefit-duration-detail')
ns_crud.add_resource(CRUD_ConfigBenefitDurationDetail_List, '/config/benefit-duration-detail-list')
ns_crud.add_resource(CRUD_ConfigBenefitDurationSet, '/config/benefit-duration-set/<int:id>', '/config/benefit-duration-set')
ns_crud.add_resource(CRUD_ConfigBenefitDurationSet_List, '/config/benefit-duration-set-list')
ns_crud.add_resource(CRUD_ConfigBenefitProductVariation, '/config/benefit-product-variation/<int:id>', '/config/benefit-product-variation')
ns_crud.add_resource(CRUD_ConfigBenefitProductVariation_List, '/config/benefit-product-variation-list')
ns_crud.add_resource(CRUD_ConfigBenefitProvision, '/config/benefit-provision/<int:id>', '/config/benefit-provision')
ns_crud.add_resource(CRUD_ConfigBenefitProvision_List, '/config/benefit-provision-list')
ns_crud.add_resource(CRUD_ConfigBenefitState, '/config/benefit-state/<int:id>', '/config/benefit-state')
ns_crud.add_resource(CRUD_ConfigBenefitState_List, '/config/benefit-state-list')
ns_crud.add_resource(CRUD_ConfigCoverage, '/config/coverage/<int:id>', '/config/coverage')
ns_crud.add_resource(CRUD_ConfigCoverage_List, '/config/coverage-list')
ns_crud.add_resource(CRUD_ConfigFactor, '/config/factor/<int:id>', '/config/factor')
ns_crud.add_resource(CRUD_ConfigFactor_List, '/config/factor-list')
ns_crud.add_resource(CRUD_ConfigFactorRule, '/config/factor-rule/<int:id>', '/config/factor-rule')
ns_crud.add_resource(CRUD_ConfigFactorRule_List, '/config/factor-rule-list')
ns_crud.add_resource(CRUD_ConfigProduct, '/config/product/<int:id>', '/config/product')
ns_crud.add_resource(CRUD_ConfigProduct_List, '/config/product-list')
ns_crud.add_resource(CRUD_ConfigProductMapperDetail, '/config/product-mapper-detail/<int:id>', '/config/product-mapper-detail')
ns_crud.add_resource(CRUD_ConfigProductMapperDetail_List, '/config/product-mapper-detail-list')
ns_crud.add_resource(CRUD_ConfigProductMapperSet_Gender, '/config/product-mapper-set-gender/<int:id>', '/config/product-mapper-set-gender')
ns_crud.add_resource(CRUD_ConfigProductMapperSet_Gender_List, '/config/product-mapper-set-gender-list')
ns_crud.add_resource(CRUD_ConfigProductMapperSet_SmokerStatus, '/config/product-mapper-set-smoker-status/<int:id>', '/config/product-mapper-set-smoker-status')
ns_crud.add_resource(CRUD_ConfigProductMapperSet_SmokerStatus_List, '/config/product-mapper-set-smoker-status-list')
ns_crud.add_resource(CRUD_ConfigProductState, '/config/product/<int:product_id>/state/<int:id>', '/config/product/<int:product_id>/state')
ns_crud.add_resource(CRUD_ConfigProductState_List, '/config/product/<int:product_id>/states')
ns_crud.add_resource(CRUD_ConfigProductVariation, '/config/product-variation/<int:id>', '/config/product-variation')
ns_crud.add_resource(CRUD_ConfigProductVariation_List, '/config/product-variation-list')
ns_crud.add_resource(CRUD_ConfigProductVariationState, '/config/product-variation-state/<int:id>', '/config/product-variation-state')
ns_crud.add_resource(CRUD_ConfigProductVariationState_List, '/config/product-variation-state-list')
ns_crud.add_resource(CRUD_ConfigProvision_Product, '/config/provision-product/<int:id>', '/config/provision-product')
ns_crud.add_resource(CRUD_ConfigProvision_Product_List, '/config/provision-product-list')
ns_crud.add_resource(CRUD_ConfigProvision_RateTable, '/config/provision-rate-table/<int:id>', '/config/provision-rate-table')
ns_crud.add_resource(CRUD_ConfigProvision_RateTable_List, '/config/provision-rate-table-list')
ns_crud.add_resource(CRUD_ConfigProvisionState, '/config/provision-state/<int:id>', '/config/provision-state')
ns_crud.add_resource(CRUD_ConfigProvisionState_List, '/config/provision-state-list')
ns_crud.add_resource(CRUD_ConfigProvisionUI, '/config/provision-ui/<int:id>', '/config/provision-ui')
ns_crud.add_resource(CRUD_ConfigProvisionUI_List, '/config/provision-ui-list')
ns_crud.add_resource(CRUD_ConfigRateGroup, '/config/rate-group/<int:id>', '/config/rate-group')
ns_crud.add_resource(CRUD_ConfigRateGroup_List, '/config/rate-group-list')
ns_crud.add_resource(CRUD_ConfigRateGroupFaceAmounts_List, '/config/rate-group-face-amounts-list')
ns_crud.add_resource(CRUD_ConfigRateTable, '/config/rate-table/<int:id>', '/config/rate-table')
ns_crud.add_resource(CRUD_ConfigRateTable_List, '/config/rate-table-list')
ns_crud.add_resource(CRUD_ConfigRelationshipMapperDetail, '/config/relationship-mapper-detail/<int:id>', '/config/relationship-mapper-detail')
ns_crud.add_resource(CRUD_ConfigRelationshipMapperDetail_List, '/config/relationship-mapper-detail-list')
ns_crud.add_resource(CRUD_ConfigRelationshipMapperSet, '/config/relationship-mapper-set/<int:id>', '/config/relationship-mapper-set')
ns_crud.add_resource(CRUD_ConfigRelationshipMapperSet_List, '/config/relationship-mapper-set-list')

ns_crud.add_resource(CRUD_RefAttrMapperType, '/ref/attr-mapper-type/<int:id>', '/ref/attr-mapper-type')
ns_crud.add_resource(CRUD_RefAttrMapperType_List, '/ref/attr-mapper-type-list')
ns_crud.add_resource(CRUD_RefBenefit, '/ref/benefit/<int:id>', '/ref/benefit')
ns_crud.add_resource(CRUD_RefBenefit_List, '/ref/benefit-list')
ns_crud.add_resource(CRUD_RefCensusStrategy, '/ref/census-strategy/<int:id>', '/ref/census-strategy')
ns_crud.add_resource(CRUD_RefCensusStrategy_List, '/ref/census-strategy-list')
ns_crud.add_resource(CRUD_RefComparisonOperator, '/ref/comparison-operator/<int:id>', '/ref/comparison-operator')
ns_crud.add_resource(CRUD_RefComparisonOperator_List, '/ref/comparison-operator-list')
ns_crud.add_resource(CRUD_RefComponentTypes, '/ref/component-type/<int:id>', '/ref/component-type')
ns_crud.add_resource(CRUD_RefComponentTypes_List, '/ref/component-type-list')
ns_crud.add_resource(CRUD_RefDataTypes, '/ref/data-type/<int:id>', '/ref/data-type')
ns_crud.add_resource(CRUD_RefDataTypes_List, '/ref/data-type-list')
ns_crud.add_resource(CRUD_RefFactorType, '/ref/factor-type/<int:id>', '/ref/factor-type')
ns_crud.add_resource(CRUD_RefFactorType_List, '/ref/factor-type-list')
ns_crud.add_resource(CRUD_RefInputTypes, '/ref/input-type/<int:id>', '/ref/input-type')
ns_crud.add_resource(CRUD_RefInputTypes_List, '/ref/input-type-list')
ns_crud.add_resource(CRUD_RefOptionality, '/ref/optionality/<int:id>', '/ref/optionality')
ns_crud.add_resource(CRUD_RefOptionality_List, '/ref/optionality-list')
ns_crud.add_resource(CRUD_RefPremiumFrequency, '/ref/premium-frequency/<int:id>', '/ref/premium-frequency')
ns_crud.add_resource(CRUD_RefPremiumFrequency_List, '/ref/premium-frequency-list')
ns_crud.add_resource(CRUD_RefProductVariation, '/ref/product-variation/<int:id>', '/ref/product-variation')
ns_crud.add_resource(CRUD_RefProductVariation_List, '/ref/product-variation-list')
ns_crud.add_resource(CRUD_RefProvision, '/ref/provision/<int:id>', '/ref/provision')
ns_crud.add_resource(CRUD_RefProvision_List, '/ref/provision-list')
ns_crud.add_resource(CRUD_RefRatingStrategy, '/ref/rating-strategy/<int:id>', '/ref/rating-strategy')
ns_crud.add_resource(CRUD_RefRatingStrategy_List, '/ref/rating-strategy-list')
ns_crud.add_resource(CRUD_RefStates, '/ref/state/<int:id>', '/ref/state')
ns_crud.add_resource(CRUD_RefStates_List, '/ref/state-list')
ns_crud.add_resource(CRUD_RefUnitCode, '/ref/unit-code/<int:id>', '/ref/unit-code')
ns_crud.add_resource(CRUD_RefUnitCode_List, '/ref/unit-code-list')

ns_crud.add_resource(CRUD_SelectionAgeBand, '/selection/age-band/<int:id>', '/selection/age-band')
ns_crud.add_resource(CRUD_SelectionAgeBand_List, '/selection/age-band-list')
ns_crud.add_resource(CRUD_SelectionBenefit, '/selection/benefit/<int:id>', '/selection/benefit')
ns_crud.add_resource(CRUD_SelectionBenefit_List, '/selection/benefit-list')
ns_crud.add_resource(CRUD_SelectionBenefitDuration, '/selection/benefit-duration/<int:id>', '/selection/benefit-duration')
ns_crud.add_resource(CRUD_SelectionBenefitDuration_List, '/selection/benefit-duration-list')
ns_crud.add_resource(CRUD_SelectionBenefitRateTable, '/selection/rate-table/<int:plan_id>')
ns_crud.add_resource(CRUD_SelectionCensusDetail, '/selection/census-detail/<int:id>', '/selection/census-detail')
ns_crud.add_resource(CRUD_SelectionCensusDetail_List, '/selection/census-detail-list')
ns_crud.add_resource(CRUD_SelectionCensusSet, '/selection/census-set/<int:id>', '/selection/census-set')
ns_crud.add_resource(CRUD_SelectionCensusSet_List, '/selection/census-set-list')
ns_crud.add_resource(CRUD_SelectionPlan, '/selection/plan/<int:id>', '/selection/plan')
ns_crud.add_resource(CRUD_SelectionPlan_List, '/selection/plan-list')
ns_crud.add_resource(CRUD_SelectionProvision, '/selection/provision/<int:id>', '/selection/provision')
ns_crud.add_resource(CRUD_SelectionProvision_List, '/selection/provision-list')
ns_crud.add_resource(CRUD_SelectionRateGroupFaceAmounts, '/selection/rate-group-face-amounts/<int:id>', '/selection/rate-group-face-amounts')
ns_crud.add_resource(CRUD_SelectionRateGroupFaceAmounts_List, '/selection/rate-group-face-amounts-list')

ns_crud.add_resource(SelectionCensusSet_CensusBuilder, '/selection/plan/<int:plan_id>/census/build')
ns_crud.add_resource(SelectionCensusSet_UploadFile, '/selection/plan/<int:plan_id>/census/upload')
ns_crud.add_resource(Resource_RatingPremiumCalculator, '/selection/plan/<int:plan_id>/rating/premium')