export { default as ConfigProductList } from './ConfigProductList'
export { default as ConfigProductDetail } from './ConfigProductDetail'
export { default as ConfigProductDetailRatingAttributes } from './ConfigProductDetailRatingAttributes'
export { default as ConfigProductDetailRatingDistributions } from './ConfigProductDetailRatingDistributions'
export { default as ConfigProductDetailRatingStrategy } from './ConfigProductDetailRatingStrategy'
export { default as ConfigProductDetailCensus } from './ConfigProductDetailCensus'
