/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AuthPasswordImport } from './routes/auth/password'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as SelectionPlanIndexImport } from './routes/selection/plan/index'
import { Route as SelectionPlanSelectionplanidBenefitsImport } from './routes/selection/plan/$selection_plan_id/benefits'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthPasswordRoute = AuthPasswordImport.update({
  path: '/auth/password',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const SelectionPlanIndexRoute = SelectionPlanIndexImport.update({
  path: '/selection/plan/',
  getParentRoute: () => rootRoute,
} as any)

const SelectionPlanSelectionplanidBenefitsRoute =
  SelectionPlanSelectionplanidBenefitsImport.update({
    path: '/selection/plan/$selection_plan_id/benefits',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/password': {
      preLoaderRoute: typeof AuthPasswordImport
      parentRoute: typeof rootRoute
    }
    '/selection/plan/': {
      preLoaderRoute: typeof SelectionPlanIndexImport
      parentRoute: typeof rootRoute
    }
    '/selection/plan/$selection_plan_id/benefits': {
      preLoaderRoute: typeof SelectionPlanSelectionplanidBenefitsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthLoginRoute,
  AuthPasswordRoute,
  SelectionPlanIndexRoute,
  SelectionPlanSelectionplanidBenefitsRoute,
])

/* prettier-ignore-end */
